michaella23/bootcamp-collab

- .gitignore
- README.md
This PR includes:
1. Closing issue #1
2. Adding a .gitignore file to ignore IntelliJ IDE project settings and Mac OS .DS_Store folders
> [#1] Link to the Discord #study-group in the README, and add .gitignore

- assets/css/base.css
- assets/css/index.css
- assets/javascript/app.js
Hi Micha, 
Issues solved:
- Solved issue #2 
Additions:
- Added folder basic structure
- Created separate CSS files for better management
- Added the js file
> Issue #2 sorted + folder structure

- README.md
This PR is to add the missing Netlify live app URL to the README.md
> Add live app URL to README.md

- assets/css/base.css
Added a background color to the body in 'base.css'.
> Changed bg color

- index.html
I linked the missing stylesheet to the HTML to have the styling applied.
> [#11] Fix missing styles by linking index.css in index.html

- assets/css/base.css
Adding Karla font to the page.
> [#7] Add and apply Google Font Karla to the entire page

- CONTRIBUTING.md
- README.md
This PR adds a CONTRIBUTING.md file that details why to contribute, how to contribute, and contribution guidelines. It also links to the file in the README.md.
> [#14] Contributing guide

- STYLE-GUIDE.md
> fix: #21 fix typos

- index.html
Addressing issue "The title bar is looking a bit empty, add a favicon [#25](https://github.com/michaella23/bootcamp-collab/issues/25)"
> icecream icon added to the tab

- assets/javascript/contributors.js
I created this file for contributors to add their information. This will make a good 'first issue' for anyone who wants to contribute and isn't sure how to get started.
> Created `contributors.js`, added my info.

- assets/javascript/app.js
Corresponding issue: Display current time [#28](https://github.com/michaella23/bootcamp-collab/issues/28)
> Add-greeting-phrase-to-local-time

- assets/javascript/app.js
- assets/javascript/contributors.js
Adding my own info to contributors
> Info added to contribtions.js

- assets/css/index.css
added a fun sliding rainbow text effect to the Current Local Time text!
> Rainbow text

- assets/css/index.css
Trying to delete folder that was created when working in GitHub desktop
> Rainbow fix

- assets/javascript/app.js
To see changes you need navigate to the page after 5pm
> night-theme-added

- assets/css/base.css
- assets/css/index.css
- assets/javascript/app.js
- assets/javascript/contributors.js
- index.html
Hi Micha 👋, 
I went ahead and made the site responsive, I also changed a class name from being heading-primary to heading-secondary as it was incorrectly used, just to avoid confusion for other students seeing this and or being confused as to why an h2 has a heading primary and not a heading secondary class.
I'll try and make an effort every so often to adjust the sites responsiveness if it has been done so already, so not to put pressure on newer students
> Issue #54 add site responsiveness

- assets/css/index.css
- index.html
> [#51] Add hover effects to links

- assets/css/index.css
- assets/javascript/app.js
- index.html
Corresponding issue:
Add toggle for light and dark themes [#30](https://github.com/michaella23/bootcamp-collab/issues/30)
> toggle light or dark theme of the page

- assets/css/index.css
- assets/javascript/app.js
- assets/javascript/contributors-component.js
- assets/javascript/contributors.js
- index.html
Addressing the issues in PRs below:
issues 27 20 34 54 implemented with New Contributors Feature https://github.com/michaella23/bootcamp-collab/pull/60
Refactoring theme and greeting logics #61
> Refactoring Theme logic PART2

- assets/javascript/app.js
Here is a minor fix for:
Refactoring Theme logic PART2 #63
Simplified smooth logic, removed redundant lines of code.
> Minor fix of theme switch

- CONTRIBUTING.md
Fixed a couple of typos and adjusted the height of the screenshot in General Guidelines
> spelling, punctuation, image height

- CONTRIBUTING.md
In order to reduce confusion and improve communication, I have added guidelines that would have contributors request assignment to existing issues or newly created issues.
> Added several new Guidelines. Please review.

- README.md
Code of Conduct was pretty vague. Additions aim to improve communication and encourage patience as we all work together.
> Added to Code of Conduct

- STYLE-GUIDE.md
- assets/javascript/contributors.js
> fix: fix some typos

- CONTRIBUTING.md
Noticed that the screenshot image was getting super squished on the mobile view. Removing width and height in an effort to improve that view.
> Removed style attributes for image.

- CODE_OF_CONDUCT.md
Just my attempt to further the checklist found in the insights tab.
> Create: #81 CODE_OF_CONDUCT.md

- assets/javascript/contributors-component.js
- assets/javascript/contributors.js
Added the feature where random contributors are displayed on page load, and when loading more contributors. I also went ahead an adjusted the load amount to 6 contributors instead of 4, can even push it up to 8 if wanted.
I left test data in the contributors files, just so we can easily test this feature and make sure no duplicates are being added
.
I think when we all satisfied with the result, we can go ahead and remove them.
There is a currentContributors variable left behind, with a few console.logs maybe, will remove and clean up the code once everyone is happy with the outcome.
> feat: #73 random contributors solved

- CODE_OF_CONDUCT.md
Part of the efforts:
Code of conduct update - Managing conflict #85
> Manage conflict recommendations section

- CODE_OF_CONDUCT.md
ref: https://github.com/michaella23/bootcamp-collab/pull/86#pullrequestreview-1495613150
> Manage conflict recommendations moved  to line 38

- assets/css/base.css
- assets/css/index.css
- assets/javascript/app.js
- index.html
Changed the header design a bit to achieve a nice looking nav bar. Theme switch should be working for the header/nav.
The element is not yet responsive.
> #100 created nav element

- assets/javascript/contributors.js
I added my name to the list of contributors.
> Updated contributor list

- assets/css/about.css
- html/about.html
- index.html
I created a separate `html` file, which is `about.html`. Content is temporary! 😂 I thought it might be nice to add some more pages to this site that we can navigate to and build/style from scratch.
> Created 'About' page

- assets/javascript/about.js
- assets/javascript/app.js
- assets/javascript/theme.js
- html/about.html
Overview of changes made:
- Extracted all theme logic from `app.js` to `theme.js`
- Created `about.js` and linked it to `about.html`
- Add localStorage functionality for persisting current theme through refresh and page change
- Add fallback using current time to set theme if nothing in localStorage
> [#111] Issue theme btn

- assets/css/about.css
- assets/css/open-source-projects.css
- html/about.html
Changes:
- Fixed up the [Open Source Projects](http://localhost:5501/html/open-source-projects.html)
and [About](http://localhost:5501/html/about.html) pages to make them responsive
Note:
My commit history on this is a bit weird because I had some issues with pushing this branch. I tried git rebase but couldn't figure out how to remove the redundant commits. Would love to hear more about how I might go about fixing that
> [#54]Issue mobile responsiveness

- assets/css/open-source-projects.css
Make the projects details stand out.
> Improve the open source projects styling

- assets/javascript/paulo.js
I deleted paulo.js in response to issue #136
> deleted paulo.js

- assets/javascript/open-source-projects.js
Added 2 open-source projects to the list.
> [#139] Added 2 projects

- assets/css/base.css
- assets/css/index.css
- assets/css/nav.css
- html/about.html
- html/open-source-projects.html
- index.html
This update addresses issue #144  by fixing the Nav menu's appearance and preventing the overlay of nav and content.
> updated the nav menu UI
